In [1]:
import numpy as np

In [2]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [3]:
x=[1,2,3,'bhavya']

In [4]:
x

[1, 2, 3, 'bhavya']

In [5]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [6]:
y=np.array([3,4,5])

In [7]:
x=[3,4,5]

In [8]:
type(x),type(y)

(list, numpy.ndarray)

In [9]:
x=[3,4,5]
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
y/5

array([0.6, 0.8, 1. ])

In [11]:
y=np.array([2,3,4,8.6,"data science"])

In [12]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [13]:
y

array(['2', '3', '4', '8.6', 'data science'], dtype='<U32')

In [14]:
for i in range(1,10):
  print(np.random.randint(0,30))

29
29
5
1
16
13
5
1
17


In [15]:
np.random.randint(0,10,(6,6))

array([[9, 6, 9, 2, 3, 4],
       [0, 6, 8, 5, 4, 2],
       [3, 9, 0, 7, 6, 9],
       [1, 3, 2, 5, 6, 1],
       [3, 4, 7, 0, 3, 6],
       [8, 1, 6, 3, 5, 3]])

In [16]:
data=np.random.randint(0,200,(5,5))

In [17]:
data

array([[  7,  76, 133, 181,  65],
       [ 29, 117,   5, 166, 182],
       [127,  39, 110,   7,  25],
       [ 29, 141,  23, 149,  31],
       [140, 104, 136, 108, 116]])

In [18]:
data[0:3,4:5]

array([[ 65],
       [182],
       [ 25]])

In [19]:
data[0:2,3:5]

array([[181,  65],
       [166, 182]])

In [20]:
data[1:3,4:5]

array([[182],
       [ 25]])

In [21]:
data[-5:-4,-5:-4]

array([[7]])

In [22]:
data[-5:-4,-5:-3]

array([[ 7, 76]])

In [23]:
data[-4:-2,-3:-2]

array([[  5],
       [110]])

In [24]:
data[-2:-1,-2:-1]

array([[149]])

In [25]:
data[0,:]

array([  7,  76, 133, 181,  65])

In [26]:
data

array([[  7,  76, 133, 181,  65],
       [ 29, 117,   5, 166, 182],
       [127,  39, 110,   7,  25],
       [ 29, 141,  23, 149,  31],
       [140, 104, 136, 108, 116]])

In [27]:
data[:,0]

array([  7,  29, 127,  29, 140])

In [28]:
data.shape

(5, 5)

In [29]:
data.size

25

In [30]:
data.T

array([[  7,  29, 127,  29, 140],
       [ 76, 117,  39, 141, 104],
       [133,   5, 110,  23, 136],
       [181, 166,   7, 149, 108],
       [ 65, 182,  25,  31, 116]])

In [31]:
data

array([[  7,  76, 133, 181,  65],
       [ 29, 117,   5, 166, 182],
       [127,  39, 110,   7,  25],
       [ 29, 141,  23, 149,  31],
       [140, 104, 136, 108, 116]])

In [32]:
x=2

In [33]:
data**2

array([[   49,  5776, 17689, 32761,  4225],
       [  841, 13689,    25, 27556, 33124],
       [16129,  1521, 12100,    49,   625],
       [  841, 19881,   529, 22201,   961],
       [19600, 10816, 18496, 11664, 13456]])

In [34]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [35]:
x

array([[2, 2, 4],
       [4, 4, 1],
       [7, 6, 3]])

In [36]:
y

array([[9, 5, 2],
       [6, 0, 9],
       [6, 3, 5]])

In [37]:
np.add(x,2)

array([[4, 4, 6],
       [6, 6, 3],
       [9, 8, 5]])

In [38]:
np.multiply(x,2)

array([[ 4,  4,  8],
       [ 8,  8,  2],
       [14, 12,  6]])

In [39]:
np.divide(x,2)

array([[1. , 1. , 2. ],
       [2. , 2. , 0.5],
       [3.5, 3. , 1.5]])

In [40]:
np.floor_divide(x,2)

array([[1, 1, 2],
       [2, 2, 0],
       [3, 3, 1]])

In [41]:
np.floor_divide(x,3)

array([[0, 0, 1],
       [1, 1, 0],
       [2, 2, 1]])

In [42]:
np.exp(x)

array([[   7.3890561 ,    7.3890561 ,   54.59815003],
       [  54.59815003,   54.59815003,    2.71828183],
       [1096.63315843,  403.42879349,   20.08553692]])

In [43]:
np.log(x)

array([[0.69314718, 0.69314718, 1.38629436],
       [1.38629436, 1.38629436, 0.        ],
       [1.94591015, 1.79175947, 1.09861229]])

In [44]:
np.pow(x,4)

array([[  16,   16,  256],
       [ 256,  256,    1],
       [2401, 1296,   81]])

In [45]:
np.pow(x,7)

array([[   128,    128,  16384],
       [ 16384,  16384,      1],
       [823543, 279936,   2187]])

In [46]:
np.random.rand(5,5)

array([[0.59266634, 0.62741293, 0.89292978, 0.71468231, 0.59604356],
       [0.26821138, 0.94937075, 0.13664037, 0.33192703, 0.67872746],
       [0.78339407, 0.38063148, 0.19975299, 0.91803034, 0.48934923],
       [0.32636733, 0.12296585, 0.70510273, 0.48820296, 0.85285504],
       [0.99800856, 0.92830028, 0.41985072, 0.7990739 , 0.68495862]])

In [47]:
np.random.randn(1600,1300).std()

np.float64(1.0003182436808835)

In [48]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
np.zeros(19)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [50]:
np.zeros((9,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.ones((8,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
data=np.random.randint(0,40,(20,10))

In [54]:
data

array([[15,  5,  4, 20,  4,  5, 24, 10,  8, 21],
       [ 3, 20, 16, 29,  2, 15,  6, 26, 19, 24],
       [18, 24, 33, 13, 31, 28, 32,  6, 23, 12],
       [21, 32, 31, 17, 15, 30, 18, 28, 14, 14],
       [28,  0, 30, 36, 13, 21, 35, 37, 11, 24],
       [12,  4, 35, 36,  0,  7, 36, 19, 10, 37],
       [16, 11, 35, 26, 16, 30, 11, 33, 28, 36],
       [32, 35, 17, 19, 30, 14, 17, 14, 29, 11],
       [ 2, 10, 11,  8, 21, 25, 26, 38,  2,  1],
       [31, 33,  0, 23,  0, 22, 19,  3,  0,  4],
       [ 9, 21, 35,  3, 38,  1, 22, 18, 13,  2],
       [20, 32,  0, 18, 12, 10, 15, 30, 23,  1],
       [29, 35, 21,  1, 29, 32, 39, 27, 28, 38],
       [ 9, 32, 28,  5, 23, 32,  0, 38, 13, 15],
       [16, 14, 17, 17, 36, 12, 36, 26, 27, 12],
       [ 4, 12,  8, 27, 14,  8,  9, 12,  6, 26],
       [19,  1, 39, 27, 29,  7, 27, 38, 21, 33],
       [28,  7,  0, 36,  6,  7,  3, 10, 16, 13],
       [19,  2, 24,  5, 33, 15,  1,  8, 22, 15],
       [20, 23, 30, 38, 28,  6, 30,  3, 27, 17]])

In [60]:
print(data.sum())
print(data.min())
print(data.max())

245
0
9


In [61]:
data.argmax()

np.int64(8)

In [62]:
data=np.random.randint(0,10,(9,6))

In [63]:
data

array([[3, 9, 3, 6, 9, 0],
       [6, 1, 0, 0, 0, 1],
       [6, 8, 2, 2, 7, 5],
       [6, 0, 8, 9, 1, 1],
       [6, 6, 3, 1, 8, 0],
       [0, 2, 4, 9, 3, 1],
       [5, 6, 8, 7, 2, 9],
       [2, 6, 4, 0, 6, 1],
       [0, 4, 3, 5, 0, 0]])

In [64]:
data.sum(axis=1)

array([30,  8, 30, 25, 24, 19, 37, 19, 12])

In [65]:
data.sum(axis=0)

array([34, 42, 35, 39, 36, 18])

In [66]:
data

array([[3, 9, 3, 6, 9, 0],
       [6, 1, 0, 0, 0, 1],
       [6, 8, 2, 2, 7, 5],
       [6, 0, 8, 9, 1, 1],
       [6, 6, 3, 1, 8, 0],
       [0, 2, 4, 9, 3, 1],
       [5, 6, 8, 7, 2, 9],
       [2, 6, 4, 0, 6, 1],
       [0, 4, 3, 5, 0, 0]])

In [67]:
data.argmin(axis=1)

array([5, 2, 2, 1, 5, 0, 4, 3, 0])

In [69]:
data.max(axis=0)

array([6, 9, 8, 9, 9, 9])