In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,8,(4,4))

In [ ]:
data

array([[1, 1, 7, 6],
       [4, 1, 6, 2],
       [4, 3, 4, 4],
       [7, 7, 1, 5]])

In [ ]:
data.sum()

np.int64(63)

In [ ]:
data.sum(axis=1)

array([15, 13, 15, 20])

In [ ]:
data.sum(axis=0)

array([16, 12, 18, 17])

In [ ]:
data.max()

np.int64(7)

In [ ]:
data

array([[1, 1, 7, 6],
       [4, 1, 6, 2],
       [4, 3, 4, 4],
       [7, 7, 1, 5]])

In [ ]:
data.max(axis=1)

array([7, 6, 4, 7])

In [ ]:
data.argmax(axis=1)

array([2, 2, 0, 0])

In [ ]:
data=np.random.randint(0,80,(6,6))

In [ ]:
data

array([[40, 66, 55, 64, 69, 60],
       [58, 57, 50, 31,  3, 49],
       [24, 27, 31,  2, 41, 50],
       [ 5, 78, 77, 35, 11,  3],
       [66, 12,  9, 48, 22, 49],
       [71, 62, 28,  3, 35, 41]])

In [ ]:
data.sum(axis=1).argmin()+1

np.int64(3)

In [ ]:
data.sum(axis=1)

array([354, 248, 175, 209, 206, 240])

In [ ]:
data.sum(axis=0)

array([264, 302, 250, 183, 181, 252])

In [ ]:
data.sum()

np.int64(1432)

In [ ]:
data=np.random.randint(10,100,(10,5))

In [ ]:
data.sum(axis=0).argmax()+1

np.int64(5)

In [ ]:
data.sum(axis=0)

array([523, 518, 660, 547, 711])

In [ ]:
data.sum(axis=0)[3:].sum()

np.int64(1258)

In [ ]:
data[:,2:5].sum()

np.int64(1918)

In [ ]:
data

array([[94, 68, 67, 96, 93],
       [38, 40, 53, 43, 56],
       [33, 20, 52, 45, 11],
       [36, 44, 58, 45, 82],
       [91, 77, 84, 98, 58],
       [95, 38, 32, 10, 95],
       [75, 51, 79, 45, 76],
       [25, 39, 62, 80, 63],
       [18, 63, 77, 62, 82],
       [18, 78, 96, 23, 95]])

In [ ]:
data.sum(axis=0).max()

np.int64(711)

In [ ]:
data.sum(axis=0).min()

np.int64(518)

In [ ]:
data.sum(axis=0).max()-data.sum(axis=0).min()

np.int64(193)

In [ ]:
data=np.random.randint(0,8,8)

In [ ]:
data.mean()

np.float64(3.75)

In [ ]:
data

array([7, 7, 1, 5, 5, 2, 3, 0])

In [ ]:
np.median(data)

np.float64(4.0)

In [ ]:
data

array([7, 7, 1, 5, 5, 2, 3, 0])

In [ ]:
np.quantile(data,0.24)

np.float64(1.68)

In [ ]:
np.quantile(data,0.45)

np.float64(2.15)

In [ ]:
np.quantile(data,0.43)

np.float64(5.0)

In [ ]:
np.median(data)

np.float64(5.0)

Descriptive Statistics

In [ ]:
np.std(data)

np.float64(2.331844763272204)

In [ ]:
np.var(data)


np.float64(5.4375)

In [ ]:
data=np.random.randint(0,6,(6,2))

In [ ]:
np.corrcoef(data.T)

array([[ 1.        , -0.21248647],
       [-0.21248647,  1.        ]])

In [ ]:
v1=np.arange(2,16)

In [ ]:
v2=np.arange(50,60)

In [ ]:
v1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
v2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
x=[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
x.reverse()
v2=np.array(x)
v2

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

In [ ]:
data=v1
data=v2

In [ ]:
np.corrcoef(data.T)

array([[ 1.        , -0.21248647],
       [-0.21248647,  1.        ]])

In [ ]:
data=np.random.randint(0,15,(6,6))

In [ ]:
np.corrcoef(data)

array([[ 1.        , -0.63650907, -0.10336647, -0.55084047,  0.55731604,
         0.04958911],
       [-0.63650907,  1.        , -0.38325063, -0.02047879,  0.24662934,
         0.26455545],
       [-0.10336647, -0.38325063,  1.        ,  0.53555911, -0.40219983,
        -0.3340808 ],
       [-0.55084047, -0.02047879,  0.53555911,  1.        , -0.67697703,
        -0.62143186],
       [ 0.55731604,  0.24662934, -0.40219983, -0.67697703,  1.        ,
         0.5070462 ],
       [ 0.04958911,  0.26455545, -0.3340808 , -0.62143186,  0.5070462 ,
         1.        ]])