In [1]:
pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 76.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 15.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
openc

In [1]:
from gensim.models import Word2Vec

In [3]:
text='''OpenAI offers two powerful third-generation embedding model \n (denoted by -3 in the model ID). Read the embedding v3 announcement blog post for more details.

Usage is priced per input token. Below is an example of pricing pages of text per US dollar \n (assuming ~800 tokens per page):'''

In [4]:
text=text.splitlines()

In [5]:
from gensim.utils import simple_preprocess

In [6]:
tokenized_sentences=[simple_preprocess(i) for  i in text]

In [7]:
model=Word2Vec(sentences=tokenized_sentences,vector_size=100,min_count=1,workers=4)

In [8]:
model.wv['token']

array([ 6.4139427e-03, -8.9433510e-03, -7.3626805e-03, -1.7451746e-03,
        1.6926106e-03, -1.0297776e-03, -5.1979469e-03,  6.5804734e-03,
        8.7671066e-03, -7.4127107e-03,  9.8117245e-03,  7.3596286e-03,
       -7.4511557e-03, -1.8969476e-03,  4.2624106e-03,  7.0755305e-03,
       -3.6594016e-03, -6.9699669e-03,  4.7277077e-03, -9.0706367e-03,
       -5.8521419e-03, -1.2839115e-03,  5.5028759e-03, -5.6774337e-03,
        4.7912686e-03, -4.2187402e-04,  2.6579988e-03,  6.4008101e-03,
        1.4225976e-03,  7.7153081e-03, -3.1696417e-04, -8.2632182e-03,
        9.2067467e-03, -4.8640380e-03,  4.7284928e-03, -3.8856671e-03,
       -7.3300060e-03, -6.5096384e-03,  4.6622995e-03, -6.5978116e-04,
        1.4567585e-03, -8.9380397e-03, -5.1544760e-03, -6.0545527e-03,
        8.4224902e-03, -8.7169968e-03,  5.0189532e-03, -8.6420495e-04,
        1.8847718e-04,  8.7983655e-03, -3.5925221e-03, -6.9498350e-03,
        7.4203021e-04,  7.7515524e-03,  9.1244029e-03, -3.6976137e-03,
      

In [9]:
model.wv.most_similar("token")

[('by', 0.23808519542217255),
 ('offers', 0.15623702108860016),
 ('denoted', 0.15593242645263672),
 ('input', 0.14902126789093018),
 ('usage', 0.1445314586162567),
 ('openai', 0.13130754232406616),
 ('per', 0.10867001116275787),
 ('read', 0.10192841291427612),
 ('embedding', 0.0811353400349617),
 ('priced', 0.07833761721849442)]

In [10]:
text

['OpenAI offers two powerful third-generation embedding model ',
 ' (denoted by -3 in the model ID). Read the embedding v3 announcement blog post for more details.',
 '',
 'Usage is priced per input token. Below is an example of pricing pages of text per US dollar ',
 ' (assuming ~800 tokens per page):']

In [11]:
model.save("word2vec_model.model")

In [12]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

# The sentences to encode
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 384]

# 3. Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings)
print(similarities)
# tensor([[1.0000, 0.6660, 0.1046],
#         [0.6660, 1.0000, 0.1411],
#         [0.1046, 0.1411, 1.0000]])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(3, 384)
tensor([[1.0000, 0.6660, 0.1046],
        [0.6660, 1.0000, 0.1411],
        [0.1046, 0.1411, 1.0000]])


In [13]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

# The sentences to encode
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 384]

# 3. Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings)
print(similarities)
# tensor([[1.0000, 0.6660, 0.1046],
#         [0.6660, 1.0000, 0.1411],
#         [0.1046, 0.1411, 1.0000]])

(3, 384)
tensor([[1.0000, 0.6660, 0.1046],
        [0.6660, 1.0000, 0.1411],
        [0.1046, 0.1411, 1.0000]])


In [15]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("ProsusAI/finbert")

# The sentences to encode
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 384]

# 3. Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings)
print(similarities)
# tensor([[1.0000, 0.6660, 0.1046],
#         [0.6660, 1.0000, 0.1411],
#         [0.1046, 0.1411, 1.0000]])

(3, 768)
tensor([[1.0000, 0.8016, 0.5712],
        [0.8016, 1.0000, 0.6246],
        [0.5712, 0.6246, 1.0000]])


In [16]:
import tensorflow_hub as hub
import tensorflow as tf

In [17]:
elmo=hub.load("https://tfhub.dev/google/elmo/3")

In [18]:
embeedings=elmo.signatures["default"](tf.constant(text))

In [19]:
text

['OpenAI offers two powerful third-generation embedding model ',
 ' (denoted by -3 in the model ID). Read the embedding v3 announcement blog post for more details.',
 '',
 'Usage is priced per input token. Below is an example of pricing pages of text per US dollar ',
 ' (assuming ~800 tokens per page):']

In [20]:
len(text)

5

In [21]:
embeedings["word_emb"].shape

TensorShape([5, 18, 512])

In [22]:
embeedings["word_emb"][0][:10].numpy()

array([[-0.07185397, -0.65482634,  0.50845486, ...,  0.37564188,
        -0.34296072, -0.2713275 ],
       [-0.18025804, -0.04970091,  0.15603805, ...,  0.36208516,
         0.9945922 ,  0.95432997],
       [-0.00798023,  0.2644317 , -0.07581489, ...,  0.19201614,
        -0.24893184,  0.5197941 ],
       ...,
       [-0.08522522, -0.13059646,  0.12390487, ...,  0.07749507,
        -0.04289508, -0.04951264],
       [-0.08522522, -0.13059646,  0.12390487, ...,  0.07749507,
        -0.04289508, -0.04951264],
       [-0.08522522, -0.13059646,  0.12390487, ...,  0.07749507,
        -0.04289508, -0.04951264]], dtype=float32)