Questions

In [ ]:
"1. Total number of transactions": retail_np_array.shape[0],
"2. Total revenue generated": np.sum(totals)
"3. Average order value": np.mean(totals),
"4. Product with the highest total price": products[np.argmax(totals)],
"5. Product with the lowest total price": products[np.argmin(totals)],
"6. Average price of products": np.mean(prices),
"7. Total quantity sold": np.sum(quantities),
"8. Most frequently purchased product": np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[1])],
"9. Number of unique products": len(np.unique(products)),
"10. Number of unique customers": len(np.unique(customer_ids)),
"11. List all products sold": products.tolist(),
"12. Revenue per product": {prod: np.sum(totals[products == prod]) for prod in np.unique(products)},
"13. Quantity sold per product": {prod: np.sum(quantities[products == prod]) for prod in np.unique(products)},
"14. Highest price of a product": np.max(prices),
"15. Lowest price of a product": np.min(prices),
"16. Products sold more than once": products[quantities > 1].tolist(),
"17. Customers who bought more than one item": customer_ids[quantities > 1].tolist(),
"18. Total spent by CustomerID 1002": np.sum(totals[customer_ids == 1002]),
"19. Products priced above 1000": products[prices > 1000].tolist(),
"20. Products with total >= 2000": products[totals >= 2000].tolist()

In [ ]:
import numpy as np

#Retail dataset as numpy array
retail_np_array=np.array([
    [1001, "Laptop", 1, 50000, 50000],
    [1002, "Mouse", 2, 500, 1000],
    [1003, "Keyboard", 1, 1000, 1000],
    [1004, "Monitor", 2, 7000, 14000],
    [1005, "Headphones", 1, 2000, 2000],
], dtype=object)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
#Extracting columns
customer_ids = retail_np_array[:, 0]
products = retail_np_array[:, 1]
qunatities = retail_np_array[:, 2].astype(int)
prices = retail_np_array[:, 3].astype(int)
totals = retail_np_array[:, 4].astype(int)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
retail_np_array.shape[0]

5

In [ ]:
retail_np_array.shape

(5, 5)

In [ ]:
np.sum(totals),

(np.int64(68000),)

In [ ]:
np.mean(totals),

(np.float64(13600.0),)

In [ ]:
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
products[np.argmax(totals)]

'Laptop'

In [ ]:
products[np.argmin(totals)]

'Mouse'

In [ ]:
np.mean(prices)

np.float64(12100.0)

In [ ]:
np.sum(qunatities)

np.int64(7)

In [ ]:
np.unique(products, return_counts=True)

(array(['Headphones', 'Keyboard', 'Laptop', 'Monitor', 'Mouse'],
       dtype=object),
 array([1, 1, 1, 1, 1]))

In [ ]:
np.unique(products, return_counts=True)[0]

array(['Headphones', 'Keyboard', 'Laptop', 'Monitor', 'Mouse'],
      dtype=object)

In [ ]:
[np.argmax(np.unique(products, return_counts=True)[1])]

[np.int64(0)]

In [ ]:
np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[0])]

'Mouse'

In [ ]:
np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[1])]

'Headphones'

In [ ]:
len(np.unique(products))

5

In [ ]:
len(np.unique(customer_ids))

5

In [ ]:
products.tolist()

['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones']

In [ ]:
{prod: np.sum(totals[products == prod]) for prod in np.unique(products)}

{'Headphones': np.int64(2000),
 'Keyboard': np.int64(1000),
 'Laptop': np.int64(50000),
 'Monitor': np.int64(14000),
 'Mouse': np.int64(1000)}

In [ ]:
{prod: np.sum(qunatities[products == prod]) for prod in np.unique(products)}

{'Headphones': np.int64(1),
 'Keyboard': np.int64(1),
 'Laptop': np.int64(1),
 'Monitor': np.int64(2),
 'Mouse': np.int64(2)}

In [ ]:
 np.max(prices)

np.int64(50000)

In [ ]:
np.min(prices)

np.int64(500)

In [ ]:
products[qunatities > 1].tolist(),

(['Mouse', 'Monitor'],)

In [ ]:
 customer_ids[qunatities > 1].tolist()

[1002, 1004]

In [ ]:
np.sum(totals[customer_ids == 1002])

np.int64(1000)

In [ ]:
products[prices > 1000].tolist()




['Laptop', 'Monitor', 'Headphones']

In [ ]:
products[totals >= 2000].tolist()

['Laptop', 'Monitor', 'Headphones']