In [75]:
import numpy as np

In [76]:
data=np.random.randint(0,20,5)


In [78]:
data

array([ 9,  4,  0, 16, 12])

In [80]:
data+3

array([12,  7,  3, 19, 15])

In [81]:
x=np.random.randint(0,10,(4,5))

In [84]:
x

array([[4, 2, 0, 8, 9],
       [8, 5, 3, 9, 0],
       [7, 7, 4, 3, 8],
       [5, 7, 0, 9, 9]])

In [86]:
y=np.random.randint(0,10,(1,5))

In [92]:
x

array([[4, 2, 0, 8, 9],
       [8, 5, 3, 9, 0],
       [7, 7, 4, 3, 8],
       [5, 7, 0, 9, 9]])

In [93]:
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]


[7, 1, 3]

In [94]:
y

array([[0, 9, 7, 7, 5]])

In [95]:
x+y

array([[ 4, 11,  7, 15, 14],
       [ 8, 14, 10, 16,  5],
       [ 7, 16, 11, 10, 13],
       [ 5, 16,  7, 16, 14]])

In [99]:
x=np.random.randint(0,10,(4,1))

In [103]:
x

array([[7],
       [6],
       [1],
       [3]])

In [109]:
y

array([4, 8, 5])

In [110]:
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]




[3, 3, 9, 9]

In [111]:
5555
1111
1111
5555

5555

In [112]:
x+y

array([[11, 15, 12],
       [10, 14, 11],
       [ 5,  9,  6],
       [ 7, 11,  8]])

In [113]:
x

array([[7],
       [6],
       [1],
       [3]])

In [115]:
y

array([4, 8, 5])

In [21]:
import numpy as np

In [24]:
data=np.loadtxt("/content/sample_data/sample.txt")

In [25]:
data

array([2.31652612e+09, 3.82753823e+09, 3.65427820e+09, 9.07865674e+09,
       5.34247256e+09, 8.64662654e+09, 6.48735465e+09, 6.94364535e+09,
       6.43547386e+09])

In [26]:
data=np.loadtxt("/content/sample_data/sample file.txt")

In [27]:
data

array([3.45362783e+09, 6.55789909e+09, 1.24356789e+09, 3.55477941e+09,
       3.46528280e+09])

In [28]:
data.shape

(5,)

In [29]:
data=np.random.randint(0,20,5)

In [30]:
data

array([11,  2,  9, 11, 11])

In [31]:
data.cumsum()

array([11, 13, 22, 33, 44])

In [32]:
data.cumprod()

array([   11,    22,   198,  2178, 23958])

In [33]:
data=np.random.randint(0,20,(4,4))

In [34]:
data

array([[ 2, 16, 10,  5],
       [ 0,  5, 18, 15],
       [ 9,  6, 18, 14],
       [12, 11, 16, 13]])

In [35]:
data

array([[ 2, 16, 10,  5],
       [ 0,  5, 18, 15],
       [ 9,  6, 18, 14],
       [12, 11, 16, 13]])

In [36]:
data.cumsum(axis=1)

array([[ 2, 18, 28, 33],
       [ 0,  5, 23, 38],
       [ 9, 15, 33, 47],
       [12, 23, 39, 52]])

In [37]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [39]:
a=np.random.choice([20,30,40,50,60],size=3)
a

array([50, 50, 60])

In [40]:
a=np.random.choice([20,30,40,50,60],size=3,replace=True)
a

array([30, 30, 20])

In [41]:
a=np.random.choice([20,30,40,50,60],size=3,replace=False)
a

array([40, 60, 50])